apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: rimskiy-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: rimskiy.example.com

images:
  - name: ghcr.io/rimskiy/backend
    newTag: prod
  - name: ghcr.io/rimskiy/web
    newTag: prod
  - name: ghcr.io/rimskiy/notification-worker
    newTag: prod
